keys:
  - &admin   age1qpdtj40mumh690hcjd3uwjz6ushhpmeed5lwngc8kf5ylcyh5skqg33py6
  - &server1 age14h6cpmyt8z5d66kyyv6c8n9l5rjdcwcc6h8fsnnzk95vxf5hnvls2tvfk8
  - &machine age1gqvp4ks4cdsfg607fykzc49slqasetmegrf5k95ervruecccku9s8vd2tm

creation_rules:
  - path_regex: secrets/server1\.yaml$
    key_groups:
      - age:
          - *admin
          - *server1
  - path_regex: secrets/machine\.yaml$
    key_groups:
      - age:
          - *admin
          - *machine
