keys:
  - &admin_aletheios age1pggxm6nxeurz7ajp8a8elhfcmgp8lrshtf3dmuxjycxpsg4suqsqpkv07r
  - &server1 age1t0m37muuydtmqj9zkduxjc7rsjgq9zvjaahf6rngveq4nnzlapdqnwgqq5

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *admin_aletheios
          - *server1
